sudo: required
services:
  - docker
before_install:
  - docker build -t anishsinha1/complex -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true anishsinha1/complex yarn test --coverage

after_success:
  - docker build -t anishsinha1/complex-client ./client
  - docker build -t anishsinha1/complex-server ./server
  - docker build -t anishsinha1/complex-worker ./worker
  - docker build -t anishsinha1/complex-nginx ./nginx
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push anishsinha1/complex-client
  - docker push anishsinha1/complex-server
  - docker push anishsinha1/complex-worker
  - docker push anishsinha1/complex-nginx

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "complex-docker"
  env: "Complexdocker-env"
  bucket_name: "elasticbeanstalk-us-east-1-697480332228"
  bucket_path: "docker-complex"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
